core/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from core.views.auth import LoginView, RegisterView
from core.views.author import AuthorsView, AuthorDetailView, AuthorCreateView, AuthorDeleteView
from core.views.books import DetailBookView, BookCreateView, BookDeleteView
from core.views.favorites import FavoritesView, AddToFavoriteView, RemoveFromFavoriteView
from core.views.genres import GenreCreateView
from core.views.base import *

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='index'), name='logout'),
    path('book/<int:pk>', DetailBookView.as_view(), name='detail_book'),
    path('authors/', AuthorsView.as_view(), name='authors'),
    path('author/<int:pk>', AuthorDetailView.as_view(), name='detail_author'),
    path('book/create/', BookCreateView.as_view(), name='book_create'),
    path('book/delete/<int:pk>', BookDeleteView.as_view(), name='book_delete'),
    path('author/create/', AuthorCreateView.as_view(), name='author_create'),
    path('author/delete/<int:pk>', AuthorDeleteView.as_view(), name='author_delete'),
    path('genre/create/', GenreCreateView.as_view(), name='genre_create'),
    path('favorites/', FavoritesView.as_view(), name='favorites'),
    path('add-to-favorite/<int:pk>/', AddToFavoriteView.as_view(), name='add-to-favorite'),
    path('remove-from-favorite/<int:pk>/', RemoveFromFavoriteView.as_view(), name='remove-to-favorite')

]

liblesson/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from rest_framework_jwt.views import refresh_jwt_token, obtain_jwt_token

from liblesson.endpoints import ChangePasswordEndpoint

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/change-email/', ChangePasswordEndpoint.as_view()),
    path('api/api-token-auth/', obtain_jwt_token),
    path('api/api-token-refresh/', refresh_jwt_token),
    path('', include('core.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class AbstractModel(models.Model):
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class User(AbstractUser, AbstractModel):
    pass


class Genre(AbstractModel):
    name = models.CharField(max_length=255, verbose_name='Название')

    def __str__(self):
        return self.name


class Book(AbstractModel):
    name = models.CharField(max_length=255, verbose_name='Название')
    author = models.ForeignKey('Author', on_delete=models.CASCADE, verbose_name='Автор', related_name='books')
    description = models.TextField(verbose_name='Описание')
    genres = models.ManyToManyField(Genre, verbose_name='Жанры', related_name='books')
    image = models.ImageField(null=True, blank=True, verbose_name='Изображение')
    price = models.FloatField(verbose_name='Цена', default=0.0)
    users = models.ManyToManyField(User, related_name='favorites')

    def __str__(self):
        return f'{self.name} [{self.author if self.author else "Не выбран"}]'

    class Meta:
        ordering = ['-date_created']


class Author(AbstractModel):
    AGES_CHOICE = (('male', 'Мужчина'), ('female', 'Женщина'))
    first_name = models.CharField(max_length=255, verbose_name='Имя')
    last_name = models.CharField(max_length=255, verbose_name='Фамилия')
    date_of_birth = models.DateField(verbose_name="Дата рождения")
    sex = models.CharField(choices=AGES_CHOICE, max_length=10, verbose_name='Пол')
    author_image = models.ImageField(null=True, blank=True, verbose_name='Изображение')

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

    class Meta:
        ordering = ['-date_created']

core/forms.py
from django import forms
from django.contrib.auth import authenticate
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.core.exceptions import ValidationError

from core.models import Book, Author, Genre, User

class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = User
        fields = '__all__'
        field_classes = {'email': forms.EmailField}


class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = User
        fields = '__all__'
        field_classes = {'email': forms.EmailField}

class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = '__all__'


class AuthorForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = '__all__'


class GenreForm(forms.ModelForm):
    class Meta:
        model = Genre
        fields = '__all__'


class LoginForm(forms.Form):
    username = forms.CharField(max_length=150)
    password = forms.CharField(max_length=150, widget=forms.PasswordInput())

    def clean(self):
        cleaned_data = super().clean()
        username = cleaned_data.get("username")
        password = cleaned_data.get("password")
        user = authenticate(username=username, password=password)
        if user is None:
            self.add_error('username', 'Неверный логин или пароль')
        return cleaned_data


class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'email')

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Passwords don\'t match.')
        return cd['password2']


class FilterForm(forms.Form):
    price_min = forms.FloatField(required=False, label='Максимальная цена:')
    price_max = forms.FloatField(required=False, label='Минимальная цена:')
    CHOICES = (
        ("price_desc", "По убыванию цены"),
        ("price_asc", "По возрастанию цены"),
    )
    sorting = forms.ChoiceField(choices=CHOICES, label='Сортировать:')

core/views/author.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.views import View
from django.views.generic import TemplateView, DetailView

from core.forms import AuthorForm
from core.models import Author
from mixins.auth import AbsLoginMixin


class AuthorsView(TemplateView):
    template_name = 'core/authors.html'

    def get(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        context['authors'] = Author.objects.all()

        return render(request, self.template_name, context)


class AuthorDetailView(DetailView):
    template_name = 'core/author-detail.html'
    model = Author


class AuthorCreateView(AbsLoginMixin, TemplateView):
    template_name = 'core/create-author.html'

    def get_context_data(self, **kwargs):
        context = super(AuthorCreateView, self).get_context_data(**kwargs)
        context['form'] = AuthorForm(self.request.POST or None, self.request.FILES or None)
        return context

    def post(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        if context['form'].is_valid():
            author = context['form'].save()
            return redirect(reverse('detail_author', kwargs={'pk': author.pk}))
        else:
            return render(request, self.template_name, context)


class AuthorDeleteView(AbsLoginMixin, View):
    def get(self, request, *args, **kwargs):
        author_pk = kwargs.get('pk')
        author = get_object_or_404(Author, pk=author_pk)
        author.delete()
        return redirect(reverse('index'))

core/views/base.py
import urllib

from django.db.models import Q
from django.shortcuts import render
from django.views.generic import TemplateView

from core.forms import FilterForm
from core.models import Book
from core.utils.logs import log_record


class IndexView(TemplateView):
    template_name = 'core/index.html'

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['form'] = FilterForm(self.request.POST or None)
        context['books'] = Book.objects.all()

        return context

    def post(self, request, *args, **kwargs):
        log_record(request, 'actions', 'Пользователь чо-то делает')
        query = Q()
        context = self.get_context_data(**kwargs)
        filter_book = context.get('form')
        books = context.get('books')
        if filter_book.is_valid():
            price_max = filter_book.cleaned_data['price_max']
            price_min = filter_book.cleaned_data['price_min']
            if price_max is not None:
                books = books.filter(price__lte=price_max)
            if price_min is not None:
                books = books.filter(price__gte=price_min)
            sorting = filter_book.cleaned_data.get('sorting')
            if sorting == 'price_desc':
                books = Book.objects.filter(query).order_by('-price')
            elif sorting == 'price_asc':
                books = Book.objects.filter(query).order_by('price')

        context['books'] = books
        context['form'] = filter_book
        return render(request, self.template_name, context)

core/views/books.py
from django.shortcuts import redirect, render, get_object_or_404
from django.urls import reverse
from django.views import View
from django.views.generic import DetailView, TemplateView

from core.forms import BookForm
from core.models import Book
from mixins.auth import AbsLoginMixin


class DetailBookView(DetailView):
    template_name = 'core/detail-book.html'
    model = Book


class BookCreateView(AbsLoginMixin, TemplateView):
    template_name = 'core/book-create.html'

    def get_context_data(self, **kwargs):
        context = super(BookCreateView, self).get_context_data(**kwargs)
        context['form'] = BookForm(self.request.POST or None, self.request.FILES or None)
        return context

    def post(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        if context['form'].is_valid():
            book = context['form'].save()
            return redirect(reverse('detail_book', kwargs={'pk':book.pk}))
        else:
            return render(request, self.template_name, context)


class BookDeleteView(AbsLoginMixin, View):

    def get(self, request, *args, **kwargs):
        book_pk = kwargs.get('pk')
        book = get_object_or_404(Book, pk=book_pk)
        book.delete()
        return redirect(reverse('index'))

core/views/favorites.py
from django.db.models import Q
from django.shortcuts import redirect, render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import View
from django.views.generic import DetailView, TemplateView

from core.forms import BookForm
from core.models import Book
from mixins.auth import AbsLoginMixin



class AddToFavoriteView(View):
    def get(self, request, *args, **kwargs):
        book = get_object_or_404(Book, pk=kwargs.get('pk'))
        self.request.user.favorites.add(book)
        next_page = request.GET.get('next')
        if next_page:
            return HttpResponseRedirect(next_page)
        else:
            return redirect('index')

class RemoveFromFavoriteView(View):
    def get(self, request, *args, **kwargs):
        book = get_object_or_404(Book, pk=kwargs.get('pk'))
        self.request.user.favorites.remove(book)
        next_page = request.GET.get('next')
        if next_page:
            return HttpResponseRedirect(next_page)
        else:
            return redirect('index')

class FavoritesView(TemplateView):
    template_name = 'core/favorite-books.html'
    # context_object_name = 'books_list'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data( **kwargs)
        context['view_name'] = 'favourites'

        return context

    # def get_queryset(self):
    #     query = Q()
    #
    #     return self.request.user.favorites.filter(query)

core/views/genres.py
from django.shortcuts import redirect, render
from django.urls import reverse
from django.views.generic import TemplateView

from core.forms import GenreForm
from mixins.auth import AbsLoginMixin


class GenreCreateView(AbsLoginMixin, TemplateView):
    template_name = 'core/genre-create.html'

    def get_context_data(self, **kwargs):
        context = super(GenreCreateView, self).get_context_data(**kwargs)
        context['form'] = GenreForm(self.request.POST or None, self.request.FILES or None)
        return context

    def post(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        if context['form'].is_valid():
            genre = context['form'].save()
            return redirect(reverse('index'))
        else:
            return render(request, self.template_name, context)

core/templates/core/author-detail.html
{% extends 'core/base.html' %}
{% block content %}
    <h1>Подробнее об авторе</h1>
    <p>Имя: <strong>{{ author.first_name }}</strong></p>
    <p>Фамилия: <strong>{{ author.last_name }}</strong></p>
    <figure>
    {% if author.author_image %}
        <img src="{{ author.author_image.url }}" alt="Изображение {{ author.first_name }}" height="150" width="100">
    {% endif %}
    </figure>

    <p>Дата рождения: {{ author.date_of_birth|date:"Y-m-d" }}</p>
    <p>Пол: {{ author.get_sex_display }}</p>
    <a href="{% url 'author_delete' author.pk %}">Удалить...</a>
    <hr>
    <p>Все книги автора:</p>
    {% for book_ in author.books.all %}
        {% include 'core/blocks/book-card.html' with book=book_ %}
        <hr>
    {% endfor %}


    <a href="{% url 'authors' %}">Назад...</a>
    <br>

{% endblock %}

core/templates/core/authors.html
{% extends 'core/base.html' %}
{% block title %}
    Авторы
{% endblock %}
{% block content %}
    <h1>Список авторов</h1>
    {% for author in authors %}
        <p>{{ author.first_name }} {{ author.last_name }} <a href="{% url 'detail_author' author.id %}">Подробнее...</a></p>

        <hr>
    {% endfor %}
    <a href="{% url 'index' %}">Назад...</a>
{% endblock %}

core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Библиотека{% endblock %}</title>
</head>
<body>
<p>Количество переходов: {{ request.session.current_swap }}</p>
<p>Версия приложения: {{ request.version }}</p>
{% block content %}

{% endblock %}

</body>
</html>

core/templates/core/book-create.html
{% extends 'core/base.html' %}
{% block content %}
    <h1>Создание книги</h1>
    <form action="{% url 'book_create' %}" method="post" enctype="multipart/form-data">
        {{ form.as_p }}
        {% csrf_token %}
        <input type="submit" value="Сохранить">
    </form>
    <br>
    <a href="{% url 'index' %}">Назад...</a>
{% endblock %}

core/templates/core/create-author.html
{% extends 'core/base.html' %}
{% block content %}
    <h1>Создание автора</h1>
    <form action="{% url 'author_create' %}" method="post" enctype="multipart/form-data">
        {{ form.as_p }}
        {% csrf_token %}
        <input type="submit" value="Сохранить">
    </form>
    <br>
    <a href="{% url 'index' %}">Назад...</a>
{% endblock %}

core/templates/core/detail-book.html
{% extends 'core/base.html' %}
{% block content %}
    <h1>Подробнее о книге</h1>
    {% include 'core/blocks/book-card.html' with book=book %}
    <hr>
    {% if book in request.user.favorites.all %}
        <a href="{% url 'remove-to-favorite' book.pk %}">Убрать из избранных</a>
        {% else %}
        <a href="{% url 'add-to-favorite' book.pk %}">Добавить в избранные</a>
    {% endif %}
    <hr>
    <a href="{% url 'index' %}">Назад...</a>
{% endblock %}

core/templates/core/favorite-books.html
{% extends 'core/base.html' %}

{% block title %}
    Избранные
{% endblock %}
{% block content %}
    <h1>Список избранных книг</h1>
    {% for book in request.user.favorites.all %}
         <p>{{ book.name }} [{{ book.author }}] <a href="{% url 'detail_book' book.id %}">Подробнее...</a></p>

        <hr>
    {% endfor %}
    <a href="{% url 'index' %}">Назад...</a>
{% endblock %}

core/templates/core/genre-create.html
{% extends 'core/base.html' %}
{% block content %}
    <h1>Создание жанра</h1>
    <form action="{% url 'genre_create' %}" method="post" enctype="multipart/form-data">
        {{ form.as_p }}
        {% csrf_token %}
        <input type="submit" value="Сохранить">
    </form>
    <br>
    <a href="{% url 'index' %}">Назад...</a>
{% endblock %}

core/templates/core/index.html
{% extends 'core/base.html' %}
{% block title %}
    Добро пожаловать в лучшее приложение
{% endblock %}
{% block content %}
    <h1>Список доступных книг</h1>
    <form action="." method="post">


    </form>
    <form action="." method="post">

        {{ form.as_p }}
        {% csrf_token %}
        <p><input type="submit" value="Поиск"></p>
    </form>


    {% for book in books %}
        <p>{{ book.name }} [{{ book.author }}] <a href="{% url 'detail_book' book.id %}">Подробнее...</a></p>



        <hr>
    {% endfor %}
    <h3><a href="{% url 'authors' %}">Подробнее обо всех авторах в этой библиотеке...</a></h3>
    <hr>
    {% if request.user.is_authenticated  %}
        <h3><a href="{% url 'book_create' %}">Создать книгу</a></h3>
        <h3><a href="{% url 'author_create' %}">Создать автора</a></h3>
        <h3><a href="{% url 'genre_create' %}">Создать жанр</a></h3>
        <h3><a href="{% url 'favorites' %}">Избранные</a></h3>
        <a href="{% url 'logout' %}">Выйти</a>
    {% else %}
        <a href="{% url 'login' %}">Войти</a>
    {% endif %}

{% endblock %}

core/templates/core/login.html
{% extends 'core/base.html' %}
{% block content %}
    <form action="{% if request.GET.next %}{% url 'login' %}?next={{ request.GET.next }}{% else %}{% url 'login' %}{% endif %}" method="post">
        {{ form.as_p }}
        <input type="submit" value="Войти">
    {% csrf_token %}
    <p>Вы можете зарегистрироваться, если вас нет в системе. <a href="{% url "register" %}">Регистрация</a>.</p>
    </form>
{% endblock %}
{% block title %}
Вход
{% endblock %}

core/templates/core/registration-done.html
{% extends "core/base.html" %}

{% block title %}Welcome{% endblock %}

{% block content %}
    <h1>Welcome {{ new_user.first_name }}!</h1>
    <p>Your account has been successfully created. Now you can <a href="{% url "login" %}">log in</a>.</p>
{% endblock %}

core/templates/core/registration.html
{% extends "core/base.html" %}

{% block title %}Create an account{% endblock %}

{% block content %}
    <h1>Create an account</h1>
    <p>Please, sign up using the following form:</p>
    <form action="." method="post">
        {{ user_form.as_p }}
        {% csrf_token %}
        <p><input type="submit" value="Create my account"></p>
    </form>
{% endblock %}